name: expenses_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3
  firebase_core: ^2.27.1

  expense_repository:
    path: lib/packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          weight: 800
          style: italic
